### ISSUE TITLE
Invalid variable name - SELENIUM_JAR_PATH

### ISSUE THREAD

**Issue by arichtman** [nicknovitski/nix-develop#11] opened 2023-12-30 02:57 UTC
Hey,

Thanks for making this action, it's a really clever way to avoid verbose calls of `nix develop --command`
It seems to be choking on one of the environment variables, but the variable name looks ok.

I've run it a couple more times and it seems consistent.
Here's a link to a run with `set -x` on for debugging, maybe you have some idea about what's happening?

https://github.com/arichtman/www.richtman.au/actions/runs/7361637456/job/20039185453#step:5:185

**Comment by matttrach** [comment] 2024-01-02 22:03
I had a similar problem, but with a different variable. I am using a shell hook in my flake to initialize my dependencies. In my case, I am using tfswitch to essentially pin my terraform version and allow for quick switching between versions. When you call tfswitch to change versions it emits a message like ```switched to terraform version "1.5.7"```. The quotes in this were causing the nix-develop-gha script to mess up. I just made sure to send outputs to dev/null and it resolved the issue.

**Comment by arichtman** [comment] 2024-01-03 00:46
Thanks, I'll look into that

**Comment by nicknovitski** [comment] 2024-10-23 18:40
I'm glad I left this issue open because I just ran into it myself!!

Now that I can reproduce it, I hope that I can fix it.  In the meantime, to anyone else who sees the error `<variable name>: Invalid variable name`, the cause is probably the shellHook emitting characters to stdout which throw off my script: quotes, escape characters, possibly emoji.

**Comment by nicknovitski** [comment] 2024-10-27 18:02
Thank you @arichtman for your report, and @matttrach for identifying the cause.   The issue is now fixed in the latest release.

**Closed by nicknovitski** 2024-10-27 18:02 UTC
